//https://servertien.herokuapp.com
export const API_URL = "http://localhost:4000";

export const API_URLS = {
  REGISTER: '/users',
  LOGIN: '/users/login',
  CHECK_ACCTIVE_ACCOUNT:(token)=>`/users/login/${token}`,
  REFRES_TOKEN: '/users/refresh',
  CHEK_AUTH_USER: '/api/current',
  RESET_PASSWORD: '/users/login/forgotpassword',
  Change_Password:(data)=>`/users/login/forgotpassword/confirm/${data.token}`,
  LOADING_CART:"/users/loadingcart",
  GET_ITEM: (data)=> `/item/limit=${data.limit}/page=${data.page}/sortBy=${data.sortBy}/order=${data.order}`, 
  ADD_ITEM:'/item',
  UPDATE_ITEM:"/item",
  DELETE_ITEM:"/item/delete",
  ADD_IMAGE_ITEM:"/item/uploadImage",
  DELETE_IMAGE_ITEM:"/shopping/upload",
  UPDATE_VIEW:"/item/update-view",
  ADD_TO_CART:"/cart",
  REMOVE_TO_CART:'/cart/remove',
  CHECK_OUT:"/cart/check-out",
  LIST_HISTORY:"/history",
  LIST_HISTORY_OF_USER:(data)=>`/history/user/limit=${data.limit}/page=${data.page}`,
  EXPORT_BIllING:(data)=>`/history/export/${data.id}`,
  CANCELLING_BILLING:(data)=>`history/cancelled/${data.id}`,
  FISHISH_BILLING:(data)=>`history/finish/${data.id}`,
  DELETE_HISTORY:"/history/delete",
  SAVE_PRODUCTS: '/api/projects/checkout',
  GET_QUOTES_DATA: '/api/quotes',
  GET_ORDERS_DATA: '/api/orders',
  GET_SAVE_AS_QUOTE: (projectId) => `/api/projects/${projectId}/save-as-quote`,
  GET_ORDER_DETAILED: (orderId) => `/api/orders/${orderId}`,
  GET_CHECKOUT: (projectId) => `/api/projects/${projectId}`,
  GET_PRODUCTS_SVG: (productsId) => `/api/products/${productsId}/svg`,
  GET_SAVE_CHANGE_PRODUCT: (productsId) => `/api/products/${productsId}`,
  GET_ORDER_TYPES: '/api/orders/types/all',
  CHANGE_ORDER_TYPE: (orderId) => `/api/orders/${orderId}/change-type`,
  // tu tao
  CRAWLER_DATA:"/crawler/getdata",
  GET_TOTAL_INFOR:(data)=>`/total/getallinfor/day=${data.day}/month=${data.month}/year=${data.year}`,
  GET_INFOR_CHART:(data)=>`total/getallinfor/kind=${data.kind}`,
  GET_ALL_LIST_ORDER:(data)=>`/history/limit=${data.limit}/page=${data.page}/status=${data.status}`,
};
